import DOMPurify from 'dompurify';

/** Közös DOMPurify beállítás: bejövő levelek és kimenő HTML egyeztetése (XSS ellen). */
const EMAIL_BODY_PURIFY = {
  ALLOWED_TAGS: [
    'html',
    'head',
    'body',
    'style',
    'title',
    'p',
    'br',
    'strong',
    'em',
    'b',
    'i',
    'u',
    's',
    'strike',
    'sub',
    'sup',
    'small',
    'big',
    'a',
    'img',
    'ul',
    'ol',
    'li',
    'dl',
    'dt',
    'dd',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'blockquote',
    'pre',
    'code',
    'div',
    'span',
    'hr',
    'address',
    'center',
    'table',
    'caption',
    'thead',
    'tbody',
    'tfoot',
    'tr',
    'th',
    'td',
    'colgroup',
    'col',
    'font',
    'label',
    'abbr',
    'acronym',
    'cite',
    'dfn',
    'kbd',
    'samp',
    'var',
    'mark',
    'section',
    'article',
    'main',
    'figure',
    'figcaption',
    'noscript',
  ],
  ALLOWED_ATTR: [
    'href',
    'src',
    'alt',
    'title',
    'class',
    'style',
    'target',
    'rel',
    'width',
    'height',
    'border',
    'cellpadding',
    'cellspacing',
    'align',
    'valign',
    'bgcolor',
    'color',
    'face',
    'size',
    'colspan',
    'rowspan',
    'scope',
    'headers',
    'dir',
    'lang',
    'id',
    'name',
    'media',
    'type',
  ],
  ALLOW_DATA_ATTR: false,
  ADD_ATTR: ['target'],
  FORBID_TAGS: [
    'meta',
    'script',
    'iframe',
    'object',
    'embed',
    'form',
    'input',
    'button',
    'select',
    'textarea',
    'link',
    'base',
  ],
  ALLOWED_URI_REGEXP:
    /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp|data):|[^a-z]|[a-z+.-]+(?:[^a-z+.-:]|$))/i,
};

export function sanitizeEmailBodyHtml(html: string): string {
  return DOMPurify.sanitize(html, EMAIL_BODY_PURIFY);
}
