title = "EBC Gitleaks Config"

[extend]
useDefault = true

[[rules]]
id = "custom-env-file"
description = "Possible .env file committed"
regex = '''(?i)(api[_-]?key|secret|password|token)\s*=\s*.{6,}'''
tags = ["env", "secret"]